# Num Py

In [1]:
import numpy as np

In [2]:
import jupyterthemes

ModuleNotFoundError: No module named 'jupyterthemes'

In [ ]:
mylist = [1,2,3,4]

In [ ]:
type(mylist)

In [ ]:
np.array(mylist)

In [ ]:
myarray = np.array(mylist)

In [ ]:
myarray

In [ ]:
type(myarray)

In [ ]:
myMatrix = [[1,2,3],[3,4,5],[6,7,8]]

In [ ]:
np.array(myMatrix)

In [ ]:
np.arange(0,101,2)

In [ ]:
 np.arange(0,101,20)

In [ ]:
np.zeros((3,4))

In [ ]:
np.linspace(0,6,7)

In [ ]:
np.linspace(0,6,4)

In [ ]:
np.eye(4)

In [ ]:

np.random.rand(4,5)

In [ ]:
np.random.randn(5)

In [ ]:
np.random.randn(5,4)

In [ ]:
np.random.randint(0,101,5)

In [ ]:
np.random.randint(0,101,(4,3))

In [ ]:
np.random.seed(42)
np.random.rand(5)

In [ ]:
arr = np.arange(0,25)

In [ ]:
arr.reshape(5,5)

In [ ]:
ranarr = np.random.randint(0,100,12)

In [ ]:
ranarr.max()

In [ ]:
ranarr

In [ ]:
ranarr.min()

In [ ]:
ranarr.argmax()

In [ ]:

ranarr.dtype

In [ ]:
ranarr.shape

In [ ]:
ranarr = ranarr.reshape(3,4)

In [ ]:
ranarr.shape

In [ ]:
myarray = np.linspace(0,10,101)
print(myarray)

In [ ]:
arr = np.arange(0,11)

In [ ]:
arr

In [ ]:
arr[8]

In [ ]:
arr[1:8]

In [ ]:
arr[0:5]

In [ ]:
arr[:5]

In [ ]:
arr[5:]

In [ ]:
!jt -l

In [ ]:
!jt -t monokai -N -T -kl

In [ ]:
arr[0:5] = 100

In [ ]:
arr

In [ ]:
arr = np.arange(0,11)

In [ ]:
arr

In [ ]:
slice_of_arr = arr[0:5]

In [ ]:
slice_of_arr

In [ ]:
slice_of_arr[:] = 99

In [ ]:
slice_of_arr

In [ ]:
arr

In [ ]:
!jt -t chesterish -cellw 90% -lineh 170

In [ ]:
!jt -t onedork -fs 95 -altp -tfs 11 -nfs 115 -cellw 88% -T

In [ ]:
arr_copy = arr.copy()

In [ ]:
arr_copy[:] = 100

In [ ]:
arr_copy

In [ ]:
arr

In [ ]:
array_2d = np.array([[5,5,6],[4,7,8],[9,0,7]])


In [ ]:
arr_2d.shape

In [ ]:
arr_2d

In [ ]:
arr_2d[1,1]

In [ ]:
arr_2d[1]

In [ ]:
arr_2d[1:,1:]

In [3]:
array = np.arange(1,11)

In [4]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
array > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [7]:
bool_arr = array > 4

In [8]:
array[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [9]:
array[array>4]

array([ 5,  6,  7,  8,  9, 10])